### ISSUE TITLE
Rationalise parser arguments

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#166]
Some subparsers use the following:

    mcvirt network list

whilst others use

    mcvirt drbd --list

These should be made to use the same arguments, for consistency, as they could be confusing.

**Comment by Adimote** [comment]
`mcvirt node` doesn't throw a 'too few arguments' error, and in general I would suggest it would display the help whenever a command is missing or has too many arguments.

**Comment by joe-singleton-itdev** [comment]
**Delete vs Remove:**
* iso uses ``mcvirt iso --delete <name>`` (delete is an option)
* permissions uses ``mcvirt permission --delete-user <user> <vm>`` (same for ``--delete-owner`` and ``--delete-superuser``)
* network uses ``mcvirt network delete <name>`` (delete is an action)
* deleting a VM uses ``mcvirt delete <vm>``
* user is ``mcvirt user remove <user>``
* cluster uses ``mcvirt cluster remove-node --node <node>``
* backup uses ``mcvirt backup --delete-snapshot ..``

So it seems like the best thing would be to change all deleting/removing to use an action where the verb is 'delete'.

**Create vs Add**
* iso uses ``mcvirt iso --add-from-path <path>`` (add is an option, same for ``--add-from-url``)
* creating a vm uses ``mcvirt create <vm>`` (create is an action)
* user uses ``mcvirt user create <user>``
* permission uses ``mcvirt permission --add-user <user> <vm>`` (option, same for ``--add-owner`` and ``--add-superuser``)
* network uses ``mcvirt network create ...``
* cluster uses ``mcvirt add-node ...``
* backup uses ``mcvirt backup --create-snapshot ..``

So the most common verb is 'create' and more commands use it as an action instead of an option.

**Comment by joe-singleton-itdev** [comment]
**list vs --list**
* listing VMs uses ``mcvirt list``
* iso uses ``mcvirt iso --list``
* network uses ``mcvirt network list``
* drbd uses ``mcvirt drbd --list``

So it's a draw (personally I would prefer ``--list``). Either way this should be changed so that all commands use the same format.
